export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const UPDATE_PLACE_ID = 'UPDATE_PLACE_ID';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const PASSWORD_RESET = 'PASSWORD_RESET';