name: BuildAndDeploy
on:
  push:
    branches:
      - master
    paths:
      - admin/**

permissions:
 id-token: write
 contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
     AWS_DEFAULT_REGION: eu-west-2
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16 

    - name: Install Packages
      run: |
        cd admin
        npm install

    - name: Build React App
      run: |
        cd admin
        CI=false npm run build
        ls build/
        echo "Build complete 🏗️"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::905016994436:role/github-actions-role
        role-session-name: samplerolesession
        aws-region: ${{env.AWS_DEFAULT_REGION}}

    - name: Sync S3 & Invalidate Caches
      run: |
        aws s3 sync admin/build/ s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read
        aws cloudfront create-invalidation --distribution-id E3RNTECZAKSIOO --paths "/*"
        aws cloudfront create-invalidation --distribution-id E2LPK39VY9LLAW --paths "/*"
