name: BuildAndDeploy
on:
  push:
    branches:
      - master
    paths:
      - admin/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16 
    - name: Install Packages
      run: |
        cd admin
        npm install
    - name: Build
      run: |
        cd admin
        CI=false npm run build
        ls build/
        echo "Build complete 🏗️"
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2' 
        SOURCE_DIR: 'admin/build'
